baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'Superwell'

[params]
subtitle = 'Groundwater Economic Modeling'
description = 'Physics-based hydro-economic model for estimating groundwater cost and supply globally'
author = 'Hassan Niazi | JGCRI'

[markup.goldmark.renderer]
unsafe = true
